// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/valfre-vibes/CleanPremium.tsx": () => import("../components/mockups/valfre-vibes/CleanPremium.tsx"),
  "./components/mockups/valfre-vibes/EnergeticoBrasilian.tsx": () => import("../components/mockups/valfre-vibes/EnergeticoBrasilian.tsx"),
  "./components/mockups/valfre-vibes/IndustrialDark.tsx": () => import("../components/mockups/valfre-vibes/IndustrialDark.tsx")
};
